# version: 2
# jobs:
#   build:
#     docker:
#       # specify the version you desire here
#       # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
#       - image: circleci/python:3.6.8
#     steps:
#       - checkout
#       - run: sudo chown -R circleci:circleci /usr/local/bin
#       - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
#       - run: python3 -m venv uday_env
#       - run: source ~/uday_env/bin/activate
#       - run: pip3 install --user -r requirements.txt --compile --no-cache-dir
#       - run: pytest test/test_signin.py

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
      - image: circleci/postgres:9.6

    # working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python3 -m pytest test/test_signin.py

      - store_artifacts:
          path: test-reports
          destination: test-reports